### ISSUE TITLE
Box with authenticator numbers is gone

### ISSUE THREAD

**Issue by gkuljian** [mymindstorm/authenticator#5]
I've done something that made the box with the authentication code disappear. Now I can't get into my website. Normally when I open authenticator there's a box with digits in it. That has vanished. What did I do? Or what do I do to get it back? Thanks.

**Comment by mymindstorm** [comment]
If you go to the menu at the top left and hit `Export / Import` (don't copy and paste this here) do you see anything other than `{}`?

**Comment by gkuljian** [comment]
No. Nothing but the two parentheses. Thanks for the reply.

**Comment by mymindstorm** [comment]
I hate to break it to you, but that means you probably accidentally deleted your code. Unless you made a backup it's impossible for me to help you other than redirecting you to support for wherever you lost the account.

**Comment by gkuljian** [comment]
I have no idea what a secret is. I did uninstall the addon, and it's still
not working. You mean that's it, I can no longer use this addon? What the
hell.

**Comment by mymindstorm** [comment]
Of course you can still use it, but you will need to re-add the secret you lost.

**Comment by mymindstorm** [comment]
A secret is basically the QR code you scanned or the letters and numbers you entered to add a code

**Comment by gkuljian** [comment]
I never scanned anything. I'm lost on this one. I can only imagine what
Binance support would say when I ask them for my secret. I really don't
know what to do now. I've got the google authenticator for my phone, but I
have no phone service here. I was really depending on this addon.

**Comment by mymindstorm** [comment]
I'm a bit confused about what you are asking, I'm going to make a few things clear.

- If Google authenticator is already installed it does not need cell service. 
- You should have either added a code to another app or took a backup or took a backup of your codes as the add-on description said since these things tend to be a pain to recover.
- This extension isn't designed to be the only place for you to store your codes, I ported this to Firefox so I wouldn't have to look for my phone every time I wanted to login.
- When you enabled 2FA on Binance they gave you a recovery code that you should have saved, and if you don't have that you can [submit a ticket with them to get back access to your account](https://www.reddit.com/r/binance/comments/70sa77/deleted_google_auth_and_cant_login_to_binance/dn5kb56/?utm_content=permalink&utm_medium=front&utm_source=reddit&utm_name=binance)
- As evidenced by `{}` being empty, either through a bug or an accident your code was deleted. I cannot recover it as the extension doesn't even know it exists.

Since you say you never scanned anything how did you add the code in the first place?

**Comment by mymindstorm** [comment]
Open a ticket with them here: https://support.binance.com/hc/en-us/requests/new

**Comment by gkuljian** [comment]
God I feel like an idiot. It took so many tries to figure out how to log
in I saved the wrong 16 digit authentication code. I don't even remember
how I input that number. All I know is if I ever get back in I'm never
using the 2 step process again. Let them rip me off.

Thanks for your replies. I guess I can't use the addon anymore. Good to
hear about not needing cell reception. I may give it another try if I ever
get back on. But this has seriously caused me some upset. I'm supposed to
be on Binance trading, not goofing around with this stuff.

Yes, I did open a ticket with them. I sent my mug shot and paper pleading
to reset my account. So far they've sent 3 emails back, all without any
content. I've found a phone support that I suppose is legit, and I'm
awaiting a phone call from them now. There are a lot of people who fucked
up like I did.

**Comment by mymindstorm** [comment]
You aren't alone, when I first started using 2FA I locked myself out of an account I can't recover. You can still use this addon (you can't backup Google authenticator codes, so you won't have any chance of getting those back if you uninstall or lose your phone), just make sure to keep your secrets safe (in this extension either use the import/export menu or hover over a code and hit the button in the top right for a QR code and add that to Google authenticator). I'm going to add a confirm deletion prompt soon so something like this doesn't happen again.

Good luck trying to get your account back.
